#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEPLOY_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

RUNTIME_ENV="${DEPLOY_DIR}/env/runtime.env"
SECRETS_ENV="${DEPLOY_DIR}/env/secrets.local"

if [[ ! -f "${RUNTIME_ENV}" ]]; then
  echo "Missing ${RUNTIME_ENV}"
  exit 1
fi

if [[ ! -f "${SECRETS_ENV}" ]]; then
  echo "Missing ${SECRETS_ENV}"
  exit 1
fi

set -a
source "${RUNTIME_ENV}"
source "${SECRETS_ENV}"
set +a

require_var() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "Required variable is empty: ${name}"
    exit 1
  fi
}

urlencode() {
  python3 -c 'import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1]))' "$1"
}

require_var PUBLIC_DOMAIN
require_var REGISTRY
require_var POSTGRES_HOST
require_var POSTGRES_PORT
require_var POSTGRES_USER_SERVICE_DB
require_var POSTGRES_DATA_SERVICE_DB
require_var OBJECT_STORAGE_ENDPOINT
require_var OBJECT_STORAGE_REGION
require_var OBJECT_STORAGE_BUCKET
require_var VITE_API_BASE
require_var PUBLIC_APP_URL
require_var PUBLIC_API_BASE
require_var DATA_SERVICE_BASE_URL
require_var LLM_SERVICE_BASE_URL
require_var USER_SERVICE_DB_USER
require_var USER_SERVICE_DB_PASSWORD
require_var DATA_SERVICE_DB_USER
require_var DATA_SERVICE_DB_PASSWORD
require_var APP_SECRET_KEY
require_var INTERNAL_API_TOKEN
require_var S3_ACCESS_KEY_ID
require_var S3_SECRET_ACCESS_KEY

ENC_USER_SERVICE_DB_USER="$(urlencode "${USER_SERVICE_DB_USER}")"
ENC_USER_SERVICE_DB_PASSWORD="$(urlencode "${USER_SERVICE_DB_PASSWORD}")"
ENC_DATA_SERVICE_DB_USER="$(urlencode "${DATA_SERVICE_DB_USER}")"
ENC_DATA_SERVICE_DB_PASSWORD="$(urlencode "${DATA_SERVICE_DB_PASSWORD}")"

cat > "${DEPLOY_DIR}/env/frontend.env" <<EOF
VITE_API_BASE=${VITE_API_BASE}
EOF

cat > "${DEPLOY_DIR}/env/user_service.env" <<EOF
APP_ENV=production
LOG_LEVEL=INFO

APP_HOST=0.0.0.0
APP_PORT=8000

API_V1_PREFIX=/api/v1
PUBLIC_APP_URL=${PUBLIC_APP_URL}
CORS_ALLOW_ORIGINS=${PUBLIC_APP_URL}
TRUSTED_PROXIES=*

POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_DB=${POSTGRES_USER_SERVICE_DB}
POSTGRES_USER=${USER_SERVICE_DB_USER}
POSTGRES_PASSWORD=${USER_SERVICE_DB_PASSWORD}
POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
DATABASE_URL=postgresql+psycopg://${ENC_USER_SERVICE_DB_USER}:${ENC_USER_SERVICE_DB_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_USER_SERVICE_DB}

DATA_SERVICE_BASE_URL=${DATA_SERVICE_BASE_URL}
LLM_ENABLED=${ENABLE_LLM}
LLM_SERVICE_BASE_URL=${LLM_SERVICE_BASE_URL}

OBJECT_STORAGE_ENDPOINT=${OBJECT_STORAGE_ENDPOINT}
OBJECT_STORAGE_REGION=${OBJECT_STORAGE_REGION}
OBJECT_STORAGE_BUCKET=${OBJECT_STORAGE_BUCKET}
OBJECT_STORAGE_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
OBJECT_STORAGE_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}

SECRET_KEY=${APP_SECRET_KEY}
INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
EOF

cat > "${DEPLOY_DIR}/env/data_service.env" <<EOF
APP_ENV=production
LOG_LEVEL=INFO

APP_HOST=0.0.0.0
APP_PORT=8000

POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT}
POSTGRES_DB=${POSTGRES_DATA_SERVICE_DB}
POSTGRES_USER=${DATA_SERVICE_DB_USER}
POSTGRES_PASSWORD=${DATA_SERVICE_DB_PASSWORD}
POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE}
DATABASE_URL=postgresql+psycopg://${ENC_DATA_SERVICE_DB_USER}:${ENC_DATA_SERVICE_DB_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATA_SERVICE_DB}

OBJECT_STORAGE_ENDPOINT=${OBJECT_STORAGE_ENDPOINT}
OBJECT_STORAGE_REGION=${OBJECT_STORAGE_REGION}
OBJECT_STORAGE_BUCKET=${OBJECT_STORAGE_BUCKET}
OBJECT_STORAGE_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
OBJECT_STORAGE_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}

INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}
PGVECTOR_ENABLED=true
EOF

cat > "${DEPLOY_DIR}/env/llm_service.env" <<EOF
APP_ENV=production
LOG_LEVEL=INFO
APP_HOST=0.0.0.0
APP_PORT=8000
EOF

echo "Generated:"
echo "  - env/frontend.env"
echo "  - env/user_service.env"
echo "  - env/data_service.env"
echo "  - env/llm_service.env"